#Get the hostname of the client computer    
    $hostname = hostname

#Sets the path of each registry location to a variable
    $path1 = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    $path2 =  'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run'

#Cycles though each key and value in registry path1
    $key1 = Get-Item $path1
    $namevalues1 = $key1.GetValueNames() | 
        ForEach-Object { 
         [PSCustomObject] @{ 
            Property_Name = $_; 
            Value = $key1.GetValue($_) 
            } 
        }

#Sends reg key and value of Current Machine to text file
    Out-File -FilePath C:\Comparable.txt -InputObject $namevalues1


#Cycles though each key and value in registry path1
    $key2 = Get-Item $path2
    $namevalues2 = $key2.GetValueNames() | 
    ForEach-Object { 
        [PSCustomObject] @{ 
        Property_Name = $_; 
        Value = $key2.GetValue($_) 
        } 
    }

#Appends reg key and value of Local Machine to text file
    Out-File -FilePath C:\Comparable.txt -Append -InputObject $namevalues2

#compares registry keys and values with those in the Acceptable_Reg.txt text file 
    $final = Compare-object (get-content C:\Comparable.txt) (get-content C:\Acceptable_Reg.txt )|
    where {$_.SideIndicator -eq "<="} |
    select -ExpandProperty inputObject 

#Creates a text file with the computers Host-name as the Name of the file containing items not in acceptable.txt
    Out-File -FilePath C:\$hostname.txt -InputObject $final

#Opens up webClient and posts the file to the company Intranet 
    $url = intranet.xyzcompany.com\bad_reg.aspx
    $file = C:\$hostname.txt
    $wc = new-object System.Net.WebClient
    $wc.UploadFile($url, $file.FullName)

#Remove all files generated by the script from the client computer
    Remove-Item C:\Comparable.txt
    Remove-Item C:\Acceptable_Reg.txt
    Remove-Item C:\$hostname.txt
 
